### ISSUE TITLE
certain specifications crash firpmRS

### ISSUE THREAD

**Issue by jlwehle** [sfilip/firpm#11]
With the test case built like so:

```
  clang++ -I/usr/local/include -O2 -march=amdfam10
    -o firpm-tc-10kb firpm-tc-10kb.cxx
    -L/usr/local/lib -lfirpm -lmpfr -lgmp
```

Running it results in:

```
  START Parks-McClellan with reference scaling
  WARNING: The exchange algorithm did not converge.
  TRIGGER: Not enough alternating extrema!
  POSSIBLE CAUSE: Nmax too small
  WARNING: The exchange algorithm did not converge.
  TRIGGER: numerical instability
  POSSIBLE CAUSES: poor starting reference and/or a too small value for Nmax.
  Segmentation fault (core dumped)
```

which is to say it crashes in addition to not converging.

[firpm-tc-10kb.cxx.txt](https://github.com/sfilip/firpm/files/3909564/firpm-tc-10kb.cxx.txt)

**Comment by jlwehle** [comment]
This additional test case appears to crash firpmRS in a slightly different fashion.  You'll notice firpm (uniform initialization) works and firpmRS crashes without any messages (unlike the previous
test case).

[firpm-tc-10kc.cxx.txt](https://github.com/sfilip/firpm/files/3909842/firpm-tc-10kc.cxx.txt)

**Comment by sfilip** [comment]
It looks like this is related to the partitioned scenario from issue #10. Will attempt a fix.

**Comment by jlwehle** [comment]
Yep, more cases work.  Though there are still some cases which fail to converge and then crash firpmRS.  I understand that some things may simply not converge ... however crashing is bad.  :-)

With firpm-tc-200ka built like so:

  ```
clang++ -I/usr/local/include -O2 -march=amdfam10
      -o firpm-tc-200ka firpm-tc-200ka.cxx
	  -L/usr/local/lib -lfirpm -lmpfr -lgmp
```

Running it results in:

```
  Read 384 frequency bands
  Filter degree 358
  START Parks-McClellan with uniform initialization
  WARNING: The exchange algorithm did not converge.
  TRIGGER: exceeded iteration threshold of 100
  POSSIBLE CAUSES: poor starting reference and/or a too small value for Nmax.
  Iteration count = NC
  FINISH Parks-McClellan with uniform initialization

  START Parks-McClellan with reference scaling
  WARNING: The exchange algorithm did not converge.
  TRIGGER: exceeded iteration threshold of 100
  POSSIBLE CAUSES: poor starting reference and/or a too small value for Nmax.
  Segmentation fault (core dumped)
```

This example involves a fair number of bands which is read from the two datafiles supplied with the firpm-tc-200ka.cxx ... I haven't had luck producing a smaller testcase.

Initial triage shows in pm.cpp we get near the bottom of firpm around line 975, just before:

  ```
h.resize(n+1u);
  if(n % 2 == 0) {
```

with n=358, deg=179, and output.h.size()=90.  The crash is presumably due to running off the end of output.h in the for loop.

[firpm-tc-200ka.zip](https://github.com/sfilip/firpm/files/3919943/firpm-tc-200ka.zip)

**Comment by jlwehle** [comment]
Here's a somewhat smaller case which crashes.

With firpm-tc-10kd built like so:

  clang++ -I/usr/local/include -O2 -march=amdfam10
      -o firpm-tc-10kd firpm-tc-10kd.cxx
	  -L/usr/local/lib -lfirpm -lmpfr -lgmp

Running it results in:

  START Parks-McClellan with uniform initialization
  WARNING: The exchange algorithm did not converge.
  TRIGGER: exceeded iteration threshold of 100
  POSSIBLE CAUSES: poor starting reference and/or a too small value for Nmax.
  Iteration count = NC
  FINISH Parks-McClellan with uniform initialization

  START Parks-McClellan with reference scaling
  WARNING: The exchange algorithm did not converge.
  TRIGGER: exceeded iteration threshold of 100
  POSSIBLE CAUSES: poor starting reference and/or a too small value for Nmax.
  Segmentation fault (core dumped)

[firpm-tc-10kd.cxx.txt](https://github.com/sfilip/firpm/files/3920345/firpm-tc-10kd.cxx.txt)

**Comment by sfilip** [comment]
Totally agree that crashing is bad and will see how to fix this. :-) 

I should probably add a paragraph about when to use the different flavors of firpm in the README, but reference scaling is meant to be used for high degree/length filters wrt to the number of bands, since it attempts to follow the asymptotic distribution of the reference points (i.e., the equioscillation nodes).

The examples here do not really fit that bill (the number of bands is quite large and the number of taps is really small, by comparison).  I have to admit that I haven't seen anyone attempt to use so many bands before.

**Comment by jlwehle** [comment]
I'm using / abusing your implementation to synthesize CIC compensation filters ... I probably could get away specifying fewer and wider bands.

Thanks for the explanation regarding when to use reference scaling.

I tend to run all three (uniform, referencing scaling, and AFP) against my specifications just to exercise them / see if any of them misbehave / crash

**Comment by sfilip** [comment]
Sorry for taking so long to address this, was busy with other projects. I pushed a change that doesn't allow the use of reference scaling when the nb of taps is too small compared to the nb of band edges. In such a case the code will default to the uniform version.

Not totally related, but I will try to update fquantizer in January after the winter break. If you are interested in fixed-point coefficient FIR filters we recently put online with some collaborators a MILP-based tool that is able to design optimized FIR filters using shift and add operations.

The repository: https://gitlab.com/filteropt/firopt
Accompanying preprint: https://arxiv.org/abs/1912.04210

There might still be some crash causing bugs to iron out there as well, for which I apologize now.

**Comment by jlwehle** [comment]
No problem, and thanks for the info regarding the FIR "shift and add" as well as your thoughts regarding updating fquantizer.

Progress ... though there are still some cases that crash reference scaling.

While firpm-tc-10kd now says:

```
  ...
  Switching to a uniform initialization strategy
  ...
```

and doesn't crash, firpm-tc-10ke built like so:

```
  clang++ -I/usr/local/include -O2 -march=amdfam10
      -o firpm-tc-10ke firpm-tc-10ke.cxx
	  -L/usr/local/lib -lfirpm -lmpfr -lgmp

```
does crash ... this test case uses the same bands as firpm-tc-10kd with a different number of taps.

Running it results in:

```
START Parks-McClellan with uniform initialization
WARNING: The exchange algorithm did not converge.
TRIGGER: exceeded iteration threshold of 100
POSSIBLE CAUSES: poor starting reference and/or a too small value for Nmax.
Iteration count = NC
FINISH Parks-McClellan with uniform initialization

START Parks-McClellan with reference scaling
WARNING: The exchange algorithm did not converge.
TRIGGER: exceeded iteration threshold of 100
POSSIBLE CAUSES: poor starting reference and/or a too small value for Nmax.
init2.c:52: MPFR assertion failed: ((p) >= 1 && (p) <= ((mpfr_prec_t) ((((mpfr_uprec_t) -1) >> 1) - 256)))
Abort (core dumped)
```
[firpm-tc-10ke.cxx.txt](https://github.com/sfilip/firpm/files/3981772/firpm-tc-10ke.cxx.txt)

**Comment by jlwehle** [comment]
Interestingly with ntaps = 359 both uniform & referencing scaling fail to converge with referencing scaling actually crashing.

However with ntaps = 139 both uniform & referencing scaling are successful.

**Comment by sfilip** [comment]
Thanks! It might happen that certain vector sizes (namely output.h - the set of Chebyshev expansion coefficients that are used to actually compute the final tap values) might not match the value expected when convergence issues arise. I've added a test to detect this and stop the program. Can you check to see if there are still crashes on your end?

Strangely enough, the MPFR assertion fail you were getting in the output is not present on my machine. 

Also, did you intend a transition band between 0.008 and 0.00866667 in this last example or is that an oversight?

**Comment by jlwehle** [comment]
That did the trick ... the various filter specifications I'm currently playing with no longer crash.

The extra transition band you noticed is not in my original specification, it was accidentally introduced when I created the reduced test case from the original filter specification.
