### ISSUE TITLE
Certain filter specifications crash Nov 20, 2019 firpm_mp

### ISSUE THREAD

**Issue by jlwehle** [sfilip/firpm#9]
With the test case built like so:

  clang++ -I/usr/local/include -O2 -march=amdfam10
    -o firpm-tc-10k firpm-tc-10k.cxx
    -L/usr/local/lib -lfirpm -lmpfr -lgmp

Running it results in:

  ./firpm-tc-10k
  START Parks-McClellan with AFP
  Segmentation fault (core dumped)

This is simplified test case using firpmAFP ... it's from
a larger version which crashes the regular firpm.
[firpm-tc-10k.cxx.txt](https://github.com/sfilip/firpm/files/3882190/firpm-tc-10k.cxx.txt)

**Comment by sfilip** [comment]
Thanks! Working on a fix for this. Out of curiosity, the transition region seems extremely large here (wrt the actual bands of interest). Is it useful in practice to have such large transition regions?

**Comment by sfilip** [comment]
Just pushed some changes that unify all three versions of the code into one template version where the mp routines are built only if mpfr and gmp are available on the system.

Regarding the example, from what I can figure, there are numerical issues when running the AFP starting reference generation code for such skewed specifications. I've added some error checking code that should spot when an invalid AFP starting reference is produced and stop the routine to avoid hard crashes.

I would also add some warning message when the user gives a specification with an extremely large transition region (when compared to the size of the actual bands of interest), since this is likely to cause numerical problems. Do you think it useful?

**Comment by jlwehle** [comment]
The intent is to use PM to generate a full band filter which can be converted to a half band filter by inserting zeros as discussed at:

 https://core.ac.uk/download/pdf/4874137.pdf

  https://dsp.stackexchange.com/questions/36190/designing-a-half-band-fir-filter-with-scilab

I'll see if I can produce a different example with a smaller transition band.

**Comment by jlwehle** [comment]
Using the updated / unified code base I haven't been able to duplicate the crash ... the additional check(s) seem to catch the issue instead of crashing.

I've attached a new test case with a smaller transition band.

With the new test case built like so:

  clang++ -I/usr/local/include -O2 -march=amdfam10
    -o firpm-tc-200k firpm-tc-200k.cxx
    -L/usr/local/lib -lfirpm -lmpfr -lgmp

Running it results in:

  START Parks-McClellan with AFP
  Final delta     = 0.00017467173944532535961
  Iteration count = 15
  FINISH Parks-McClellan with AFP

  START Parks-McClellan with AFP
  ERROR: AFP strategy failed to produce a valid starting reference
  POSSIBLE CAUSE: badly conditioned Chebyshev Vandermonde matrix

What's interesting is the two filter specifications are essentially identical ... firpm succeeds for the first specification and fails for the second.

Perhaps this is just the nature of things ... anyway I pass this along in case comparing / contrasting the two behaviors suggests something.

With regards to warning that numerical problems may occur when an extremely large transition region is provided ... sure, providing that feedback is useful.  It suggests something that the user may be able to adjust in order to get the desired results.  Otherwise to some people (including me) it's a mystery as to why things didn't work out.  Note -- I would still try to process the specification.

**Comment by jlwehle** [comment]
Here's the new test case.
[firpm-tc-200k.cxx.txt](https://github.com/sfilip/firpm/files/3890248/firpm-tc-200k.cxx.txt)

**Comment by sfilip** [comment]
Thanks. I'm going to see if I can find a workaround to avoid these failures as much as possible.

**Comment by sfilip** [comment]
For the moment I'm a bit stuck on this. All that I can think of are workarounds that are not geared towards the AFP strategy. 

An elegant initialization approach would be to try and use the result of Thm. 7 from:

http://www-math.mit.edu/~gs/papers/equiripple.pdf

about half band interpolation filters which are nearly optimal. This might work well for some examples.

**Comment by jlwehle** [comment]
For my purposes restricting things to AFP isn't that important ... I'm just looking to generate an "optimal" half band filter.

The example I supplied used AFP just because that was a simple example I ran across which failed.

**Comment by sfilip** [comment]
I suggest you stick to the other two versions for half band filters, at least for the moment.

**Comment by jlwehle** [comment]
Thanks for looking further and for the recommendation.
I'm closing this given that the original problem (the crash I initially encountered) was fixed by your changes last month.
